description: A simple application to view users made with flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ./domain
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  navigation:
    path: ./navigation



  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

name: users_app
flutter:

  uses-material-design: true
